server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      directory: C:/Users/wjdgh/IdeaProjects/Company_Project/logs
      prefix: access_log
      suffix: .log
      pattern: "%h %l %u %t \"%r\" %s %b %D"

logging:
  file:
    name: C:/Users/wjdgh/IdeaProjects/Company_Project/logs/app.log

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/company_homepage?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 2s
    socket-timeout: 5s

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.company.homepage.vo
  configuration:
    map-underscore-to-camel-case: true
