apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: company
data:
  DB_URL: "jdbc:mysql://host.docker.internal:3306/company_homepage?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
  ES_URIS: "http://host.docker.internal:9200"
