apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-app
  namespace: company
spec:
  replicas: 1
  selector:
    matchLabels:
      app: company-app
  template:
    metadata:
      labels:
        app: company-app
    spec:
      containers:
        - name: company-app
          image: localhost:5000/company-homepage:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD
            - name: SPRING_ELASTICSEARCH_URIS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ES_URIS
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
